name: Run Test for Pull Request

on:
    pull_request:
        branches:
            - master

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ ubuntu-latest, macos-latest, windows-latest ]
                php: [ 8.2, 8.3, 8.4 ]
                dependency-version: [ prefer-lowest, prefer-stable ]
        name: Tests P${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}
        steps:
            -   name: Checkout Latest Codebase
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    ini-values: error_reporting=E_ALL
                    tools: composer:v2
                    coverage: none
                    extensions: fileinfo, mbstring, intl

            -   name: Install dependencies
                run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

            -   name: Execute tests
                run: php ./vendor/bin/pest
