name: Bump version

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Releasing Version (without prefix "v")'
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Build Changelog
                id: changelog
                uses: mikepenz/release-changelog-builder-action@v5
                with:
                    configuration: ".github/changelog-configuration.json"
                    token: ${{ secrets.ACCESS_TOKEN }}
                    mode: "PR"
            -   name: Create a GitHub release
                uses: ncipollo/release-action@v1
                with:
                    tag: v${{ inputs.version }}
                    name: Release v${{ inputs.version }}
                    body: ${{ steps.changelog.outputs.changelog }}
                    token: ${{ secrets.ACCESS_TOKEN }}
